name: Build and Test
on:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: temurin
      - name: Test
        run: mvn  test
      - name: Package
        run: mvn clean package

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: temurin

      - name: Package
        run: |
          echo running package
          mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "prashudocker01"
          password: "Prashu@docker2019"
